theme = "mainroad" # hugo-academic mainroad watercss
languageCode = "it-IT"

publishDir = "public"
layoutDir = "layouts/mainroad"

customCSS = ["/static/css/customImages.css"]

[Params]
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  dateformat = "02-01-2006" # Change the format of dates to day-month-year
  post_meta = ["date", "categories", "reading_time", "translations"] # Order of post meta information


[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right" # Configure layout for list pages
  single = false # Configure layout for single pages
  sidemenu = true # Enable it in the frontmatter of single pages
  # Enable widgets in given order
  widgets = ["ddg-search", "social", "sidemenu", "categories", "taglist"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets.social]
  # Enable parts of social widget
  github = "codingepaduli"
  gitlab = "codingepaduli"
  mastodon = "mastodon"

# Custom social links
[[Params.widgets.social.custom]]
  title = "Mastodon"
  url = "https://mastodon.uno/@padulodeveloper"
  icon = "id-301021---mastodon.svg"
