theme = "mainroad" # hugo-academic mainroad watercss
languageCode = "it-IT"

publishDir = "public"
layoutDir = "layouts/mainroad"

customCSS = ["/static/css/customImages.css"]

[Params]
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  dateformat = "02-01-2006" # Change the format of dates to day-month-year

[mediaTypes]
  [mediaTypes."text/html"]
    suffixes = ["htm", "html", "HTM", "HTML"]

[markup]
  [markup.goldmark]
    [markup.highlight]
      codeFences = true
      guessSyntax = false
      tabWidth = 4
