theme = "mainroad" # hugo-academic mainroad watercss

publishDir = "public"
layoutDir = "layouts/mainroad"

[mediaTypes]
  [mediaTypes."text/html"]
    suffixes = ["htm", "html", "HTM", "HTML"]

[markup]
  [markup.goldmark]
    [markup.highlight]
      codeFences = false
      guessSyntax = false
      tabWidth = 4
