baseURL = "http://codingepaduli.github.io/"
languageCode = "it"
title = "Coding e Paduli"
paginate = "10"

theme = "mainroad" # hugo-academic mainroad watercss

[params]
  author = "codingepaduli"
  subtitle = "Ennesimo sito/blog di programmazione ed informatica in generale"
  description = "Ennesimo sito/blog di programmazione ed informatica in generale"
  toc = true # Enable Table of Contents
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  images = ["/static/wifi-5.svg"] # Twitter Cards and OpenGraph images
  post_meta = ["date", "categories", "translations"] # Order of post meta information
  mainSections = ["posts", "openSource"]
  customCSS = ["/static/css/customImages.css"]
  seoKeyword = ["coding", "programmazione", "open-source", "sviluppo", "web"]

# [[menu.main]] not needed, use "menu" in content/_index.html

[mediaTypes]
  [mediaTypes."text/html"]
    suffixes = ["htm", "html", "HTM", "HTML"]
  [mediaTypes."application/json"]
    suffixes = ["json"]

[outputs]
  page = ["HTML"] # ADD "JSON" type to generate json files

[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
    [markup.highlight]
      codeFences = true
      guessSyntax = true
      tabWidth = 4

