baseURL = "http://codingepaduli.github.io/"
defaultContentLanguage = "it"
title = "Coding e Paduli"
paginate = "20"

theme = "mainroad" # hugo-academic mainroad watercss

[params]
  author = "codingepaduli"
  subtitle = "Ennesimo sito/blog di programmazione ed informatica in generale"
  description = "Ennesimo sito/blog di programmazione ed informatica in generale"
  toc = true # Enable Table of Contents
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  images = ["/static/wifi-5.svg"] # Twitter Cards and OpenGraph images
  post_meta = ["date", "categories", "translations"] # Order of post meta information
  mainSections = ["html", "javascript", "p5js", "tools"]
  seoKeyword = ["coding", "programmazione", "open-source", "sviluppo", "web"]

# [[menu.main]] not needed, use "menu" in content/_index.html

[mediaTypes]
  [mediaTypes."text/html"]
    suffixes = ["htm", "html", "HTM", "HTML"]

[markup]
  [markup.tableOfContents]
    endLevel = 4            # The heading level to end render the table of contents
    ordered = false         # ordered or unordered list
    startLevel = 2          # The heading level to start render the table of contents
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false     # render \n as <br> elements
      unsafe = true         # render HTML code
      xHTML = false         # render as XHTML
    [markup.highlight]
      codeFences = true     # enable code fences ```
      guessSyntax = false   # guess language syntax
      tabWidth = 2          # tab width
      lineNos = false       # line number
      style = 'igor'        # highlight style
