baseURL = "http://codingepaduli.github.io/"
defaultContentLanguage = "it"
title = "Lab. informatica"
paginate = "20"

theme = "mainroad" # hugo-academic mainroad watercss

[params]
  author = "codingepaduli"
  subtitle = "Sito web del laboratorio di informatica"
  description = "Ennesimo sito/blog di programmazione ed informatica in generale"
  toc = true # Enable Table of Contents
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  images = ["/static/wifi-5.svg"] # Twitter Cards and OpenGraph images
  post_meta = ["date", "categories", "translations"] # Order of post meta information
  mainSections = ["html", "javascript", "p5js", "tools"]
  seoKeyword = ["coding", "programmazione", "open-source", "sviluppo", "web"]

# [[menu.main]] not needed, use "menu" in content/_index.html

[mediaTypes]
  [mediaTypes."text/html"]
    suffixes = ["htm", "html", "HTM", "HTML"]

[markup]
  [markup.tableOfContents]
    ordered = false         # ordered or unordered list
    startLevel = 2          # The heading level to start render the table of contents
    endLevel = 4            # The heading level to end render the table of contents
  [markup.highlight]
    codeFences = true     # enable code fences ```
    guessSyntax = false   # guess language syntax
    tabWidth = 2          # tab width
    lineNos = false       # line number
    style = 'igor'        # highlight style
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false     # render \n as <br> elements
      unsafe = true         # render HTML code
      xHTML = false         # render as XHTML
    [markup.goldmark.extensions]
      strikethrough = true
      table = true
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = false
        [markup.goldmark.extensions.extras.insert]
          enable = false
        [markup.goldmark.extensions.extras.mark]
          enable = false
        [markup.goldmark.extensions.extras.subscript]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true
      [markup.goldmark.extensions.typographer]
        leftAngleQuote = '&lt;&lt;'
        rightAngleQuote = '&gt;&gt;'
