#
# Questo file è usato solo dallo script di check-style "eslint"
#
env:
  browser: true
  commonjs: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'p5js'
  - 'p5js/sound'
  - 'plugin:jsdoc/recommended'
parserOptions:
  ecmaVersion: 11
  sourceType: module
# TODO : End-of-Life for Built-in JSDoc Support in ESLint https://eslint.org/blog/2018/11/jsdoc-end-of-life. Use eslint-plugin-jsdoc plugin instead: https://github.com/gajus/eslint-plugin-jsdoc
plugins:
  - 'jsdoc'
rules:
# Turning off eslint rule for a specific file:
# https://stackoverflow.com/questions/34764287/turning-off-eslint-rule-for-a-specific-file
  indent:
    - off
    - tab
  linebreak-style:
    - off
    - windows
  quotes:
    - off
    - double
  semi:
    - error
    - always
  no-mixed-spaces-and-tabs:
    - off
  no-console:
    - off
  no-unused-vars:
    - warn
ignorePatterns:
  - "/static/service-worker.js"

