#
# Questo file è usato solo dallo script di check-style 
# non fa parte del framework aurelia.io
#
env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
#lista di plugin necessari
plugins:
  - require-jsdoc
rules:
  indent:
    - off
    - tab
  linebreak-style:
    - off
    - windows
  quotes:
    - off
    - double
  semi:
    - error
    - always
  no-mixed-spaces-and-tabs:
    - off
  no-console:
    - warn
  no-unused-vars:
    - warn
  #regole del plugin jsdoc
  require-jsdoc:
    - warn
  valid-jsdoc:
    - warn