# See: https://github.com/github/super-linter/blob/master/TEMPLATES/.markdown-lint.yml
# See: https://github.com/github/super-linter/blob/master/docs/disabling-linters.md#markdown
# See: https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md
---
MD013: false  # line-length
MD014: false  # commands-show-output
MD022:        # blanks-around-headings
  lines_above: 1
  lines_below: 1
MD024:        # no-duplicate-heading
  siblings_only: true
MD025:        # single-title/single-h1
  front_matter_title: ""
MD026: true   # no-trailing-punctuation
MD033:
  allowed_elements:
    - div
    - a     # used in Link-subject.md file in each section
MD036: false  # no-emphasis-as-heading
MD044:        # proper-names
  code_blocks: false
  names:
    - JavaScript
    - ECMAScript
    - WebAssembly
    - TypeScript
    - ActionScript
    - JScript
    - PWA
    - EditorConfig
    - Java
    - MVC
    - Servlet
    - JSP
    - HTML
    - CSS
    - IoT
    - RGB
    - HSB
    - Wikipedia
    - UTF-8
    - OOP
    - CMS
MD046:        # code-block-style
  style: fenced
MD048:        # code-fence-style
  style: backtick
