baseURL = "http://codingepaduli.github.io/"
languageCode = "it"
title = "Coding e Paduli"

theme = "ananke"

[params]
  author = "codingepaduli"
  description = "Ennesimo sito/blog di programmazione ed informatica in generale"
