name: Run bash script

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
  # Run everyday at 4:30 AM
  - cron: "30 5 * * *"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    # Run only when you commit a message with the word '#bash'
    if: ${{ contains(github.event.head_commit.message, '#bash') }}
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Show working directory "/home/runner/work/codingepaduli/codingepaduli"
      run: pwd
    - name: Add execution permission to the script
      run: chmod +x .github/workflows/bash_script.sh
    - name: Run the script
      run: .github/workflows/bash_script.sh
