name: ESLint Checker

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
  # Run everyday at 6:00 AM
  - cron: "0 6 * * *"

jobs:
  eslint-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Installing node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Creating the NPM project
      run: npm init --yes # (info extracted from current dir)
    - name: Install ESLint (and plugins) as project dependency
      run: npm install eslint eslint-plugin-p5js
#    - name: Install ESLint
#      run: sudo npm install -g eslint
    - name: Running ESLint
      run: eslint . --config .github/.eslintrc.yml --ext .js
      # --output-file style\wrongstyle.html --format html
